// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ATS.Model
{
    public partial class Building : BaseEntity
    {
       // public int Id { get; set; }
        public string Name { get; set; }
        public DateTime ModifiedDate { get; set; }
        public bool? IsActive { get; set; }
    }
}