// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ATS.Model
{
    public partial class PersonAccess : BaseEntity
    {
      //  public int Id { get; set; }
        public DateTime TranDate { get; set; }
        public int NumberPass { get; set; }
        public int NumberFail { get; set; }
        public int NumberTotal { get; set; }
        public int? BuildingId { get; set; }
    }
}