// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LinqToDB.Mapping;
using System;
using System.Collections.Generic;
using System.Security.Policy;

namespace ATS.Model
{
    public partial class PersonAccess : BaseEntity, IEquatable<PersonAccess>
    {
        [PrimaryKey, NotNull, Identity]
        public override int Id { get; set; }
        public DateTime TranDate { get; set; }
        public int NumberPass { get; set; }
        public int NumberFail { get; set; }
        public int NumberTotal { get; set; }
        public int RemainPass { get; set; }
        public int RemainFail { get; set; }
        public int? BuildingId { get; set; }

        public override bool Equals(object obj)
        {
            return Equals(obj as PersonAccess);
        }

        public bool Equals(PersonAccess other)
        {
            return other != null &&
                   RemainPass == other.RemainPass &&
                   RemainFail == other.RemainFail &&
                   NumberTotal == other.NumberTotal &&
                   BuildingId == other.BuildingId;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(RemainPass, RemainFail, NumberTotal, BuildingId);
        }
    }
}