// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

namespace ATS.Model
{
    public partial class PersonAccess : BaseEntity
    {
        [PrimaryKey, NotNull, Identity]
        public override int Id { get; set; }
        public DateTime TranDate { get; set; }
        public int NumberPass { get; set; }
        public int NumberFail { get; set; }
        public int NumberTotal { get; set; }
        public int RemainPass { get; set; }
        public int RemainFail { get; set; }
        public int? BuildingId { get; set; }

    }
}